name: apesentacaoModular
description: "A new Flutter project. Created by Slidy"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  font_awesome_flutter: ^8.8.1
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.2.0
  flutter_modular: ^1.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
scripts :
  mobx: flutter clean & flutter pub get & flutter pub run build_runner build --delete-conflicting-outputs